[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#pest = "2.0"
#pest_derive = "2.1"
pest = { path = "./pest/pest"}
pest_derive = { path = "./pest/derive"}
lazy_static = "1.4.0"